# Directories arguments
data_dir: "full_cityscapes_res"
exp_dir:  "fcn8s_mobilenet_V2"
out_dir:  "fcn8s_mobilenet_V2"

# Data arguments
img_height:   256
img_width:    512
num_channels: 3
num_classes:  20

# Train arguments
num_epochs: 200
batch_size: 16
shuffle: True
data_mode: "experiment"
save_every: 10
test_every: 10
max_to_keep: 1
weighted_loss: True
random_cropping: False
freeze_encoder: False

# Models arguments
learning_rate:   0.0001
weight_decay: 0.0005
bias : 0.0
batchnorm_enabled: True

# Misc arguments
verbose: False

